on: push

name: build and upload artifacts

jobs:
  build:
    name: Build - ${{ matrix.platform.name }}
    strategy:
      matrix:
        platform:
          - name: Linux ${{ matrix.arch.name }}
            target: ${{ matrix.arch.name }}-unknown-linux-gnu
            os: linux
            output: libvenbind.so
        arch:
          - name: x86_64
          - name: aarch64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: cachix/install-nix-action@v26
      - uses: cachix/cachix-action@v14
        with:
          name: devenv
      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv
      - name: Build
        shell: devenv shell bash -- -e {0}
        run: |
          cargo build --release
          mkdir dist
          cp ./target/release/${{ matrix.platform.output }} ./dist/venbind-${{ matrix.platform.os }}-${{ matrix.arch.name }}.node
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform.os }}-${{ matrix.arch.name }}
          path: ./dist/venbind-${{ matrix.platform.os }}-${{ matrix.arch.name }}.node
            
