on: push

name: build and upload artifacts

jobs:
  build:
    name: Build - ${{ matrix.platform.name }}
    strategy:
      matrix:
        platform:
          # Linux
          - name: Linux x86_64
            target: x86_64-unknown-linux-gnu
            arch: x64
            os: linux
          - name: Linux aarch64
            target: aarch64-unknown-linux-gnu
            arch: arm64
            os: linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: cachix/install-nix-action@v26
      - uses: cachix/cachix-action@v14
        with:
          name: devenv
      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv
      - name: Build
        shell: devenv shell bash -- -e {0}
        run: |
          cargo build --release
          mkdir dist
          cp ./target/release/libvenkeybind.so ./dist/venkeybind-${{ matrix.platform.os }}-${{ matrix.platform.arch }}.node
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform.os }}-${{ matrix.platform.arch }}
          path: ./dist/venkeybind-${{ matrix.platform.os }}-${{ matrix.platform.arch }}.node
